#!/bin/bash
#
# Tailscale version 1.54 or later used with a Linux 6.2 or later kernel enables UDP throughput improvements via transport layer offloads.
# https://tailscale.com/s/ethtool-config-udp-gro
#

[ "$ACTION" = "ifup" -a "$INTERFACE" = "wan" ] && {
    sleep 3
    NETDEV=$(ip -o route get 101.6.6.6 | cut -f 5 -d " ")
    ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
    /etc/init.d/tailscale restart &
    /etc/init.d/log status | grep -q "running" && logger "Tailscale on $NETDEV: UDP GRO enabled" || echo "Tailscale on $NETDEV: UDP GRO enabled" > /tmp/tailscale.log
}
